INSERT INTO Rankings (fecha, puntosMes, idU)
VALUES
--('2023-08-31', (SELECT ((Consumo.energiaUsada -Consumo.energiaGen)*0.458 -(Consumo.aguaReciclada + aguaTrat)*0.21 + Consumo.emisionesGas) / (Universidad.tamanoC + Universidad.numEstudiantes) FROM Universidad INNER JOIN Consumo on Universidad.idU = Consumo.IdU WHERE Consumo.fecha = '2023-08-31' AND consumo.idU = 1),1) anahuac norte agosto 2023
--('2023-09-30', (SELECT ((Consumo.energiaUsada -Consumo.energiaGen)*0.458 -(Consumo.aguaReciclada + aguaTrat)*0.21 + Consumo.emisionesGas) / (Universidad.tamanoC + Universidad.numEstudiantes) FROM Universidad INNER JOIN Consumo on Universidad.idU = Consumo.IdU WHERE Consumo.fecha = '2023-09-30' AND consumo.idU = 1),1) anahuac norte sept 2023
--('2023-08-31', (SELECT ((Consumo.energiaUsada -Consumo.energiaGen)*0.458 -(Consumo.aguaReciclada + aguaTrat)*0.21 + Consumo.emisionesGas) / (Universidad.tamanoC + Universidad.numEstudiantes) FROM Universidad INNER JOIN Consumo on Universidad.idU = Consumo.IdU WHERE Consumo.fecha = '2023-08-31' AND consumo.idU = 2),2) anahuac sur agosto 2023
--('2023-09-30', (SELECT ((Consumo.energiaUsada -Consumo.energiaGen)*0.458 -(Consumo.aguaReciclada + aguaTrat)*0.21 + Consumo.emisionesGas) / (Universidad.tamanoC + Universidad.numEstudiantes) FROM Universidad INNER JOIN Consumo on Universidad.idU = Consumo.IdU WHERE Consumo.fecha = '2023-09-30' AND consumo.idU = 2),2) anahuac sur sept 2023
--('2023-08-31', (SELECT ((Consumo.energiaUsada -Consumo.energiaGen)*0.458 -(Consumo.aguaReciclada + aguaTrat)*0.21 + Consumo.emisionesGas) / (Universidad.tamanoC + Universidad.numEstudiantes) FROM Universidad INNER JOIN Consumo on Universidad.idU = Consumo.IdU WHERE Consumo.fecha = '2023-08-31' AND consumo.idU = 3),3) ITAM agosto 2023
--('2023-09-30', (SELECT ((Consumo.energiaUsada -Consumo.energiaGen)*0.458 -(Consumo.aguaReciclada + aguaTrat)*0.21 + Consumo.emisionesGas) / (Universidad.tamanoC + Universidad.numEstudiantes) FROM Universidad INNER JOIN Consumo on Universidad.idU = Consumo.IdU WHERE Consumo.fecha = '2023-09-30' AND consumo.idU = 3),3) ITAM sept 2023
--('2023-08-31', (SELECT ((Consumo.energiaUsada -Consumo.energiaGen)*0.458 -(Consumo.aguaReciclada + aguaTrat)*0.21 + Consumo.emisionesGas) / (Universidad.tamanoC + Universidad.numEstudiantes) FROM Universidad INNER JOIN Consumo on Universidad.idU = Consumo.IdU WHERE Consumo.fecha = '2023-08-31' AND consumo.idU = 4),4) tec agosto 2023
--('2023-09-30', (SELECT ((Consumo.energiaUsada -Consumo.energiaGen)*0.458 -(Consumo.aguaReciclada + aguaTrat)*0.21 + Consumo.emisionesGas) / (Universidad.tamanoC + Universidad.numEstudiantes) FROM Universidad INNER JOIN Consumo on Universidad.idU = Consumo.IdU WHERE Consumo.fecha = '2023-09-30' AND consumo.idU =4),4) tec sept 2023